module.exports = {
    "庄方宜": "/tempimg/zhuang.png",
    "洛茜": "/tempimg/rossi.png",
    "汤汤": "https://patchwiki.biligame.com/images/zmd/7/77/r9ebgilt12ikmtb20ubfqj80w6rc2jj.png",
    "伊冯": "https://patchwiki.biligame.com/images/zmd/a/ae/bgrz38uiuayh0gxayxkam2lhf8gctdg.png",
    "余烬": "https://patchwiki.biligame.com/images/zmd/8/8c/n88jkurosdzugukv6xuciz6qphxytgv.png",
    "别礼": "https://patchwiki.biligame.com/images/zmd/2/28/9y3t937po61v0ftfv1wdwckrmmy7sel.png",
    "洁尔佩塔": "https://patchwiki.biligame.com/images/zmd/d/de/7olcw4b97eqoxdhumsw4jp3iv3e5v9i.png",
    "管理员": "https://patchwiki.biligame.com/images/zmd/2/2b/k83yzccc6ggbhr7gesmyp7w6t6qbnvn.png",
    "艾尔黛拉": "https://patchwiki.biligame.com/images/zmd/1/12/bodmxz5xp2eg4da0d3914tb3w9ifbhk.png",
    "莱万汀": "https://patchwiki.biligame.com/images/zmd/3/33/e93ty9dxa0yj7bvzjv7gnobyjch01sz.png",
    "骏卫": "https://patchwiki.biligame.com/images/zmd/7/79/0dsllmnuiuogqq3sqo6b6wz1awan54u.png",
    "黎风": "https://patchwiki.biligame.com/images/zmd/c/c6/aevyp0nj60hthrjzrevzrxz3tsadlwn.png",
    "佩丽卡": "https://patchwiki.biligame.com/images/zmd/e/eb/d9n96qlcmd8oo8uo4jjg09mscp0xfog.png",
    "大潘": "https://patchwiki.biligame.com/images/zmd/0/0c/c5gycfqebgt9v1oro21ky5r9cy7iy01.png",
    "弧光": "https://patchwiki.biligame.com/images/zmd/5/51/2fbrjr5d5vcsfvzx11rycksoou49ib1.png",
    "昼雪": "https://patchwiki.biligame.com/images/zmd/3/35/fcuuatdl7xdu45dpwcfx0o598mf7jj7.png",
    "狼卫": "https://patchwiki.biligame.com/images/zmd/6/6f/7rhz4rt048hldc45zvf14nplxkfggnx.png",
    "艾维文娜": "https://patchwiki.biligame.com/images/zmd/6/6f/kkchudx1ub1xujq7igohgyl2ipevy8d.png",
    "赛希": "https://patchwiki.biligame.com/images/zmd/f/f1/9bvlw8gx9gs7ipokcy4nyg1rnqsnd7h.png",
    "阿列什": "https://patchwiki.biligame.com/images/zmd/a/ae/q68nd8vkgyfrsciscamf4pxcaldwqfh.png",
    "陈千语": "https://patchwiki.biligame.com/images/zmd/6/6c/1k9pdi0956hi9m7akoxpmpfxh6d8iqc.png",
    "卡契尔": "https://patchwiki.biligame.com/images/zmd/1/12/elvpqchm7ex12c6efyzq74fn96cvlft.png",
    "埃特拉": "https://patchwiki.biligame.com/images/zmd/d/de/aj9dp3zn99djovn4w39p5enibbt2qwq.png",
    "安塔尔": "https://patchwiki.biligame.com/images/zmd/a/a9/7hte56z723lyka5aprci0wv40yzi3oc.png",
    "秋栗": "https://patchwiki.biligame.com/images/zmd/7/79/fsjwh3tm7wqufchevdwz6ee9c0rcl0n.png",
    "萤石": "https://patchwiki.biligame.com/images/zmd/d/d0/id9dfypuw599dc1xx0uqexzwtgjcays.png"
};
